---
name: terraform-aws-quick-bastion
github_user: marcelocorreia
git_repo: terraform-aws-quick-bastion
github: https://github.com/{{ .github_user }}
logo: https://i2.wp.com/killscreen.com/wp-content/uploads/2016/08/bastion-gameplay.jpg?fit=700%2C396&ssl=1
docs: https://your.docs.com
linkedin: https://www.linkedin.com/in/marcelocorreia/
website: https://your.website.com
slack: https://your.slack.com/
email: EMAIL@CHANGE.ME
blueprint: terraform/module

overview: |
  TODO:// Overview

#extra_content: |
#  ### Extra

#description_file: path.to.description

description: |
  A quick bastion...

shields:
  - https://img.shields.io/github/forks/{{ .github_user }}/terraform-aws-quick-bastion.svg?flat-square
  - https://img.shields.io/github/release/{{ .github_user }}/terraform-aws-quick-bastion.svg?flat-square

tldr:
  - '[Overview](#overview)'
  - '[Description](#description)'
  - '[Usage](#usage)'
  - '[Inputs](#inputs)'
  - '[Outputs](#outputs)'
  - '[License](#license)'

usage_file: example/main.tf

#usage: |
#  ### Usage

licenses:
  - apache-license